cc_library(
    name = "landmark_port_calc",
    srcs = ["landmark_port_calc.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//mediapipe/framework:calculator_framework",
    ],
    alwayslink = 1,
)